#footprint: [[-0.445, -0.29], [-0.445, 0.29], [0.445, 0.29], [0.445, -0.29]]
robot_radius: 0.105
#layer definitions
static_layer:
    map_topic: map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser
    laser: {topic: scan, sensor_frame: velodyne, data_type: LaserScan, clearing: true, marking: true, inf_is_valid: true}

inflation_layer:
    inflation_radius: 3.0
